FROM node:20.13.1-bookworm-slim

WORKDIR /app

COPY ./nomad-rest-api/package.json .

RUN npm install --omit=dev
RUN npm install pm2 -g

COPY ./nomad-rest-api .

EXPOSE 8080

CMD ["pm2-runtime", "app.js" ]